/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Location;
import bl.GeocodingAPI;
import bl.GraphingData_big;
import bl.StringUtils;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.LinkedList;

/**
 *
 * @author Veronika
 */
public class HoehenPanel extends javax.swing.JFrame{

    /**
     * GUI Klasse für das genaue HöhenPanel Greift auf die Java-Klasse
     * GraphinData_big zu und binded dieses Panel ein ~ Veronika
     */

    private LinkedList<Location> ll;
  

    public HoehenPanel() {
        initComponents();

    }

    public HoehenPanel(LinkedList<Location> ll) {
        initComponents();

        this.setSize(Toolkit.getDefaultToolkit().getScreenSize().width, 650);
        this.ll = ll;
        
        GraphingData_big diagramm = new GraphingData_big();
        diagramm.setHoehen(ll);
        this.pan_hoehe.add(diagramm);
        pan_hoehe.paintAll(this.getGraphics());
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_hoehe = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pan_hoehe.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pan_hoehe, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoehenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoehenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoehenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoehenPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoehenPanel().setVisible(true);
            }
        });
    }

//    private LinkedList<Location> bereiteListeVor() {
//        aufbereitete_Liste = new LinkedList<Location>();
//        StringUtils su = new StringUtils();
//        String name;
//        int i = 0;
//
//        for (Location loc : ll) {
//            try {
//                if (loc.getHoehe() != 0) {
//                    name = geo_api.KoordToOrt(loc.getKoordArray()).getName();
//
//                    name = su.correctLettersFromAPI(name);
//                    //System.out.println("Name geholt: " + name);
//                    loc.setName(name);
//
//                    aufbereitete_Liste.add(loc);
//                    i++;
//                }
//            } catch (java.lang.NullPointerException ex) {
//                System.out.println("Es wurde bei einem Namen Null zurückgegeben!");
//                
//            }
//        }
//
//        return aufbereitete_Liste;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pan_hoehe;
    // End of variables declaration//GEN-END:variables

}
